### ISSUE TITLE
Unix shebangs

### ISSUE THREAD

**Issue by eush77** [juliangruber/module-calls#1]
Currently Unix shebangs are not supported:

``` bash
$ node -e 'require("module-calls")("name", "#!/usr/bin/env node")'
/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:3859
            throw e;
            ^

Error: Line 1: Unexpected token ILLEGAL
    at throwError (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:1161:21)
    at advance (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:1089:9)
    at lookahead (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:1118:18)
    at parseSourceElements (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:3057:21)
    at parseProgram (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:3096:19)
    at parse (/home/eush77/dev/fork/module-calls/node_modules/esprima/esprima.js:3843:23)
    at module.exports (/home/eush77/dev/fork/module-calls/node_modules/astw/index.js:4:41)
    at find (/home/eush77/dev/fork/module-calls/index.js:27:14)
    at [eval]:1:24
    at Object.exports.runInThisContext (vm.js:54:17)
```

I added a test for this in https://github.com/eush77/module-calls/commit/d3b0013bf0fc0d33a342b12797625347fe718dcb but we need substack/astw#9 to make it pass.

This error manifests itself in [module-usage](https://github.com/juliangruber/module-usage), for example, most of the uses of [default-pager](https://github.com/dominictarr/default-pager) are in CLIs but [module-usage](https://github.com/juliangruber/module-usage) shows none of them.

**Comment by juliangruber** [comment]
#2 :)

**Comment by eush77** [comment]
Oh, that should work, too :)
